inherit_gem:
  bixby: bixby_default.yml
AllCops:
  TargetRubyVersion: 3
  NewCops: enable
  Exclude:
    - db/**/*
    - script/**/*
    - spec/fixtures/**/*
    - vendor/**/*

Metrics/MethodLength:
  Exclude:
    - app/helpers/application_helper.rb
    - app/helpers/model_name_helper.rb

Metrics/ModuleLength:
  Exclude:
    - app/helpers/application_helper.rb
