language: ruby
rvm:
  - 2.1.1

sudo: false
cache: bundler

notifications:
  email:
    - mike.korcynski@tufts.edu

before_script:
  - cp config/database.yml.sample config/database.yml
  - cp config/fedora.yml.sample config/fedora.yml
  - cp config/solr.yml.sample config/solr.yml
  - cp config/devise.yml.sample config/devise.yml
  - cp config/jetty.yml.sample config/jetty.yml
#  - cp config/secrets.yml.sample config/secrets.yml
  - cp config/database.yml.travis config/database.yml
  - cp config/ldap.yml.sample config/ldap.yml
#  - mysql -e 'create database tdl_test'
#  - bundle exec rake db:setup
#  - bundle exec rake tufts:fixtures:refresh
  - RAILS_ENV=test bundle exec rake db:migrate --trace
#  - RAILS_ENV=test bundle exec rake db:seed --trace
  - mkdir -p tmp && export TMPDIR=tmp
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - TRAVIS=true

bundler_args: --without development debug

services:
  - mysql
