language: ruby
rvm:
  - 2.3.3

sudo: false
cache: bundler

notifications:
  email:
    - tdl-commiters@googlegroups.com

before_script:
  - mkdir -p tmp && export TMPDIR=tmp
  - cp config/database.yml.sample config/database.yml
  - cp config/fedora.yml.sample config/fedora.yml
  - cp config/blacklight.yml.sample config/blacklight.yml
  - cp config/devise.yml.sample config/devise.yml
  - cp config/jetty.yml.sample config/jetty.yml
  - cp spec/fixtures/authorities/candidates.xml tmp/candidates.xml
#  - cp config/secrets.yml.sample config/secrets.yml
  - cp config/database.yml.sample config/database.yml
#  - mysql -e 'create database tdl_test'
#  - bundle exec rake db:setup
#  - bundle exec rake tufts:fixtures:refresh
  - RAILS_ENV=test bundle exec rake db:migrate --trace
#  - RAILS_ENV=test bundle exec rake db:seed --trace
#after_script:
#  - cat jetty/jettywrapper.log
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - TRAVIS=true
    - RAILS_ENV=test

bundler_args: --without development debug

services:
  - mysql
