#!/usr/bin/env ruby
# encoding: utf-8

path = ARGV[0]
raise ArgumentError, "Must provide the directory with the authority files as an argument" unless path
require File.expand_path(File.join(File.dirname(__FILE__), '../config/environment.rb'))

Dir.glob(File.join(path, '*.xml')).each do |filename|
  puts "Importing #{filename}"
  input = Nokogiri::XML(File.new(filename))
  input.root.xpath('//auth:candidate', 'auth' => 'http://dca.tufts.edu/aas/auth').each do |candidate_node|
    name = candidate_node.attribute('name').value
    doc = {'name_tesim' => name, 'title_tesim' => name, 'title_ssi' => name, 'title_tesim' => name, 'candidate_last_name_letter_sim' => name.first.upcase, 'id' => candidate_node.attribute('id').value, 'format_ssim' => 'Candidate', 'all_text_timv' => name}
    ActiveFedora::SolrService.instance.conn.add(doc)
  end
end

ActiveFedora::SolrService.commit


