name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    #continue-on-error: ${{ matrix.experimental }}
    runs-on: ubuntu-latest

    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      DEFAULT_ADMIN_SET: 'default'
      DATA_STORAGE: ./public
      TEMP_STORAGE: ./public
      ALLOW_NOTIFICATIONS: true
      DB_NAME: elections_test
      DB_USERNAME: root
      DB_PASSWORD: root
      RAILS_MAX_THREADS: 5
      DB_HOST: localhost
      DB_PORT: 3306
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7.0']
        experimental: [false]
        #include:
        #  - ruby-version: 2.6
        #    experimental: true

    steps:
    - name: Install OS packages
      run: |
        sudo apt-get update
        sudo apt-get install unzip imagemagick ghostscript libpq-dev libxslt-dev
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler: "2.1.4" # 2.1.4 for ruby 2.7 | and 1.17.3 for ruby 2.6
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Update rubygems
      run: |
        gem update --system
        gem install bundler:2.1.4